# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 昨夜西风的博客
author:
  name: Pirate LHX
  email: piratelhx@example.com
  bio: 一个热爱技术与思考的开发者
  location: 中国
  
description: >-
  记录我的思考与发现。分享技术心得、读书笔记和生活感悟。
  
url: "https://piratelhx.github.io"
baseurl: ""

# Tale theme settings
social:
  name: Pirate LHX
  links:
    - https://github.com/piratelhx

# theme: minima
# remote_theme: chesterhow/tale  # 注释掉这行

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: "/page/:num/"

# Other settings
timezone: Asia/Shanghai

# 语言设置
lang: zh-CN

# SEO 设置
seo:
  type: Person
  name: Pirate LHX
  links:
    - https://github.com/piratelhx

# 暂时隐藏 Sass 弃用警告
sass:
  quiet_deps: true

# 评论系统（可选）
# disqus:
#   shortname: your-disqus-shortname

# Google Analytics（可选）
# google_analytics: UA-XXXXXXXX-X

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
